### ISSUE TITLE
Add social media links to footer

### ISSUE THREAD

**Issue by rgardner** [rgardner/skullhouse#14]
@JasonYao What do you think about these icons:
http://lipis.github.io/bootstrap-social/

Too bright / bootstrap-y for the site?

We could go with the icons like those at the bottom of my site:
http://www.robert-gardner.com/

**Comment by JasonYao** [comment]
Added in some social media icons that have some animation as well, just need to link them to our respective sites

**Comment by rgardner** [comment]
Twitter: https://twitter.com/NYUSkulls
LinkedIn: https://www.linkedin.com/groups/Phi-Kappa-Sigma-Delta-Phi-3883079/about
I just messaged the group about Google Plus.

**Comment by JasonYao** [comment]
I added social media icons in my last push, lemme know if you like how it looks with the animations!

**Comment by rgardner** [comment]
Sure, happy to take a look.

**Comment by rgardner** [comment]
They look great to me!

**Comment by rgardner** [comment]
![screen shot 2015-01-31 at 4 53 18 pm](https://cloud.githubusercontent.com/assets/2448476/5989978/ac74b8be-a969-11e4-95b7-50920a419292.png)

The social media icons are just floating; we can fix this in a different PR because they work for now.
