### ISSUE TITLE
Add Custom Domain Name

### ISSUE THREAD

**Issue by rgardner** [rgardner/skullhouse#3]

**Comment by JasonYao** [comment]
CNAME file can actually be done through digital ocean, and there's even extra options that they can autofill, like if we're redirecting our mail to utilize gmail. We won't be able to do anything for the CNAME file anyways before we have the domain name sent over to us

**Comment by rgardner** [comment]
Ahh ok. This was just my experience with GH pages. Good to know!

**Comment by rgardner** [comment]
I clarified the title.

**Comment by JasonYao** [comment]
I just transferred the domain name skullhouse.nyc to an account created specifically for skulls, just redirected the nameserver over to digital ocean, and added 3 records:
![records](https://cloud.githubusercontent.com/assets/3739191/5843880/cfbe529c-a17d-11e4-9828-661e26268498.png)

**Comment by JasonYao** [comment]
We can potentially also add MX records for google that allow us to utilize gmail, but let's talk with britton first to confirm that that would be something that we would want

**Comment by rgardner** [comment]
Sounds like we should hold off on email until we get pricing figured out.
