### ISSUE TITLE
Add carousel to every page

### ISSUE THREAD

**Issue by rgardner** [rgardner/skullhouse#9]

**Comment by JasonYao** [comment]
Starting now utilizing master to start from

**Comment by rgardner** [comment]
sweet, thanks for the update man.

**Comment by JasonYao** [comment]
I'm doing all my work in a separate development branch, should I just push the entire branch once I'm done, and then we can merge it later?

**Comment by rgardner** [comment]
Yes, just do `git push -u origin your-branch`, replacing your-branch with the the name of the branch you’re working on (development?)

I recommend naming your branch jason-branch-name (prefixing the branch name with your name) - this makes it a little easier to determine who’s working on what in the repo. Also, push early and push often. There is no harm in pushing your branch to GitHub. I won’t work on your branches unless you ask me to. This way, I get to see what you’re working on and can give feedback on how you’re doing it (within reason); you can do the same for me, I’m still trying to get better with bootstrap html / css.

-- 
Bob

On January 19, 2015 at 9:27:17 AM, Jason (notifications@github.com) wrote:

I'm doing all my work in a separate development branch, should I just push the entire branch once I'm done, and then we can merge it later?

**Comment by JasonYao** [comment]
All carousels added to all pages

**Comment by rgardner** [comment]
woah there Cowboy, I have questions about how you're using the php partials.
@JasonYao #13

**Comment by rgardner** [comment]
And now we're done.
